version: '3.3'

services:
  plantuml_code:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'plantuml_code'
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/plantuml/code:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  plantuml_server:
    image: 'plantuml/plantuml-server:jetty'
    container_name: 'plantuml_server'
    environment:
      PLANTUML_LIMIT_SIZE: 8192
    ports:
      - "8080:8080"
    expose:
      - "8080"